# Tink references these static-analysis-only annotations. They are not needed at runtime.
# Narrow rules generated by R8's missing_rules.txt; retain all other missing-class checks.
-dontwarn com.google.errorprone.annotations.CanIgnoreReturnValue
-dontwarn com.google.errorprone.annotations.CheckReturnValue
-dontwarn com.google.errorprone.annotations.Immutable
-dontwarn com.google.errorprone.annotations.RestrictedApi
